version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: streamplus-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - APP_URL=${APP_URL}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        ports:
            - "8001:8000"
        networks:
            - streamplus-network
        depends_on:
            - mysql
            - redis

    redis:
        image: redis:latest
        container_name: streamplus-redis
        ports:
            - "6380:6379"
        networks:
            - streamplus-network

    nginx:
        image: nginx:latest
        container_name: streamplus-nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "8000:80"
        networks:
            - streamplus-network

    mysql:
        image: mysql:8.0
        container_name: streamplus-mysql
        restart: unless-stopped
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - streamplus-network

volumes:
    mysql_data:

networks:
    streamplus-network:
        driver: bridge
